### ISSUE TITLE
[BUG] Latest Release Throws Exception When Using New Experimental Attached to SImple Calendar

### ISSUE THREAD

**Issue by claycle** [dovrosenberg/foundry-simple-weather#51] opened 2024-04-07 14:14 UTC
When using the new experimental feature to attach SImple Weather to the Simple Calendar window, the following exception is thrown when trying to display the Simple Weather window from the Simple Calendar window.

<img width="456" alt="Screenshot 2024-04-07 at 9 05 10 AM" src="https://github.com/dovrosenberg/foundry-simple-weather/assets/419840/24410c02-26d1-403c-8fdb-b0620d4dfb80">

<img width="2311" alt="Screenshot 2024-04-07 at 9 05 48 AM" src="https://github.com/dovrosenberg/foundry-simple-weather/assets/419840/533dbfe7-8e83-4384-9b94-5f344713b332">

<img width="423" alt="Screenshot 2024-04-07 at 9 11 56 AM" src="https://github.com/dovrosenberg/foundry-simple-weather/assets/419840/cbe380d3-f7c2-44d9-a715-9bc6fd5164f1">

**To Reproduce**
1. Update to Simple Weather 1.9.0.
2. Activate the "Attach to Simple Calendar" option in the Simple Weather options.
3. Restart Foundry.
4. Open the Simple Calendar window and click on the Simple Weather button.

**Expected behavior**
No exception should be thrown; the Simple Weather window should appear.

**Screenshots**
(above)

**System info (please complete the following information):**

 - macos 14.4.1
 - Arc 1.37.0 and Edge 121.0.2277.128
 - As GM
 
Foundry Virtual Tabletop: Version 11 Stable, 11.315
Game System: rqg, 3.4.2
Active Modules: 41
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0
GPU: ANGLE (ATI Technologies Inc., AMD Radeon Pro Vega 64 OpenGL Engine, OpenGL 4.1)
Max Texture Size: 16384

Scene: 3000 x 3000 | Grid Size: 100 | Padding Percentage: 0.25
Walls: 42 | Ambient Lights: 6 | Ambient Sounds: 1 | Tiles: 4 | Tokens: 19

Actors: 43 | Items: 24 | Journal Entries: 190 | Rollable Tables: 0 |
Playlists: 8 | Compendium Packs: 84 | Chat Messages: 0

**Comment by dovrosenberg** [comment] 2024-04-07 17:44
What version of Simple Calendar?  I may need to know your simple calendar settings, as I can't reproduce this (just the ones on the game settings screen for now - not all the detailed control settings).

Did you actually restart foundry or just accept the option in the settings popup to reload after adjusting the weather attachment setting?

How did you open the calendar - the toolbar on the left under journal notes or another way?

**Comment by dovrosenberg** [comment] 2024-04-07 19:16
Also, maybe see if 1.9.1 fixes it?  I didn't do anything specifically to fix it, but I made some changes around the edges of that code that might have cleaned up some problem I can't see.

**Comment by MapperD** [comment] 2024-04-07 20:31
I'm not seeing any error codes, however, the popup doesn't display when I push the button. The window does appear when it isn't connected to Simple Calendar...
Simple weather 1.9.2
Simple Calendar 2.4.13
Accepted the setting and Restarted Foundry. No luck either way.

**Comment by claycle** [comment] 2024-04-07 21:09
1.9.2 does not fix it (as @MapperD sees as well), but the error messages went away.

To answer the other questions:

1. Simple Calendar 2.4.13
2. I have SC opening per configuration option when Foundry starts. I toggled (with logout/login restart) between normal and compact (I had compact selected normally). No change. I toggled off the SC Load on Start option, logout/login, and started SC from the menu item. No change.
3. I logout/login between settings. I do *not* bounce the Foundry server. After the last setting change in #2, I bounced the entire server. No change.

**Comment by dovrosenberg** [comment] 2024-04-07 22:55
Yep - v2.4.13 broke it already :) 

Hopefully this isn't the beginning of a trend of continuous updates.  I'll work on a new release.

**Comment by dovrosenberg** [comment] 2024-04-07 23:51
OK!  I believe 1.9.3 will fix this.  And going forward, every release of SC is likely to need a new release of this package.  Depending on frequency of those, I might fall behind and will need a reminder.  :)

**Comment by dovrosenberg** [comment] 2024-04-07 23:52
Anyone following this issue please note that 1.9.2 will work with SC 2.4.3 and 1.9.3 will work with SC 2.4.13 (I've noted in the changelog/version notes which versions go together).  Versions between 2.4.3 and 2.4.13 may or may not work with one or the other, but no promises.

**Comment by dovrosenberg** [comment] 2024-04-09 01:19
Closing but please reopen if this didn't fix it for you.

**Closed by dovrosenberg** 2024-04-09 01:19 UTC
Labels: bug
