### ISSUE TITLE
[BUG] Simple Weather fails to show configuration options inside of FoundryVTT Application interface

### ISSUE THREAD

**Issue by ytnom-ctrl** [dovrosenberg/foundry-simple-weather#30] opened 2023-10-30 21:23 UTC
Simple Weather fails to show configuration options inside of FoundryVTT Application interface. 
Also does not show configuration item on main Simple Calendar toolbar (non-compact) 

Application:

<img width="335" alt="image" src="https://github.com/dovrosenberg/foundry-simple-weather/assets/66091071/e6801515-2ffe-41e0-afb0-07635e61b6bc">

Chrome WebBrowser:

<img width="487" alt="image" src="https://github.com/dovrosenberg/foundry-simple-weather/assets/66091071/af622fa8-3a96-4bb1-9ff1-2605837f1876">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome  Version 118.0.5993.118
 - Foundry Version 11 Build 313
 - Simple Weather version 1.5.2

**Additional context**

**Comment by dovrosenberg** [comment] 2023-10-30 22:01
That Simple Weather screen looks correct.  By configuration options, do you mean things like whether to output to chat, let players see the dialog, etc?  Because those are in the game settings:

![image](https://github.com/dovrosenberg/foundry-simple-weather/assets/4704591/d89fc9d4-307e-4695-b5b7-800441edbd4c)

If that's not what you meant, could you please clarify?  Thanks!

**Comment by ytnom-ctrl** [comment] 2023-10-30 22:48
Hi! Thanks for looking.
The top screenshot from my report is from within the Foundry application. I don't use Chrome browser as a GM because I'm actually sitting at the machine running the Foundry server.
It does not have the weather "gear" on the top right of the Calendar, so I cannot set the seasons, terrain, etc. Only from within the web browser. (2nd screenshot)

**Comment by dovrosenberg** [comment] 2023-10-30 23:53
Ah.  The top screenshot is actually Simple Calendar (the other module).  Note that this is a separate app and has a separate box (just black and white vs. the colored Simple Calendar screen).  The calendar side of Simple Weather looks similar to the condensed Simple Calendar display, so easy to confuse.

That said, is the Simple Weather box then not showing anywhere when you're logging in from Foundry directly?  It should appear in the same place you left it if it was showing (in the same game) in Chrome...

**Comment by ytnom-ctrl** [comment] 2023-10-30 23:56
yes, i have no view of simple calendar at all in the foundry Application.

only the configuration options for the server where you set to output to
chat.

**Comment by dovrosenberg** [comment] 2023-10-31 12:33
Did it ever work, or has it always been missing? Are you logging in as a gamemaster or player?

**Comment by ytnom-ctrl** [comment] 2023-11-03 03:21
Sorry for the delay in responding. Yes, it worked for me in 1.5.1 Logging in as Gamemaster.

**Comment by dovrosenberg** [comment] 2023-11-12 00:39
Sorry about this...

Could you try this:
* Open Foundry
* Hit F12 to open the console
* At the ">" symbol in the window that opens, type 
  * `game.settings.get('simple-weather','displayOptions')`
  * Then type `game.settings.get('simple-weather','dialogDisplay')`
  * Then type `game.settings.get('simple-weather','windowLocation')`
* Then send a screenshot of the results

If you upgrade to at least 1.6.0 you can also try setting a keybinding for opening/closing the window and see if that fixes it.

**Comment by dovrosenberg** [comment] 2023-11-13 02:36
For some other folks it came back in v1.7.2.  Could you try upgrading and see if that fixes it?  It not, I have some other ideas.

**Comment by ytnom-ctrl** [comment] 2023-11-13 02:51
Ok, I'll check it out.
On travel, back tomorrow

**Comment by dovrosenberg** [comment] 2023-12-26 15:34
Can't reproduce.  Closing for now.

**Closed by dovrosenberg** 2023-12-26 15:34 UTC
Labels: bug
