### ISSUE TITLE
[BUG] Smalltime window shown twice when simple weather is activated and using Kingmaker

### ISSUE THREAD

**Issue by kleelue** [dovrosenberg/foundry-simple-weather#52] opened 2024-04-12 20:46 UTC
If i use smalltime, simple calendar and simple weather in my foundry world, I get the widget for changing time drawn twice, but only one is useable. The simple weather window is shown correctly (I don't use the attached mode right now). 
![image](https://github.com/dovrosenberg/foundry-simple-weather/assets/66916262/e431446a-8122-449b-970f-ef84346ab958)

If i have a new world (the other one has PF2e Kingmaker installed), everything seems to be drawn correctly.
![image](https://github.com/dovrosenberg/foundry-simple-weather/assets/66916262/af30d8d3-3945-4de3-8a68-97606cae5cd8)

Do you have an idea, how to fix the behaviour in our kingmaker world, so it works as intended? The new world works, so it shouldn't be a general problem, but I don't want to move everything over onto a new one :-|
Especially as it seems that it works for my players, but not for me:
![image](https://github.com/dovrosenberg/foundry-simple-weather/assets/66916262/2b261088-c249-43a1-9d37-3b474e22125a)

 - hosted and accessed with Windows 11
 - Edge
 - Foundry 11.315
 - Logged in as a GM in both instances, tested as player on kingmaker with no visible issues

**Comment by dovrosenberg** [comment] 2024-04-13 10:46
This will be tricky since you can't reproduce it in a new world.  I'm also not at all sure that Simple Weather could cause this.  Do you let players see the SimpleWeather dialog?  If not, one thing to try would be if you turn on the setting "can players see dialog?" in the KingMaker world and see if that causes the problem to occur for players in that world.  That would at least give us a hint.

Also - are all of the modules (not just these 3) that you have running in kingmaker and the new world the same other than Kingmaker?

**Comment by dovrosenberg** [comment] 2024-05-09 10:26
Closing for now, but let me know if you tried the tests above.

**Closed by dovrosenberg** 2024-05-09 10:26 UTC
Labels: bug, can't reproduce
