### ISSUE TITLE
[Request] Trigger custom roll tables to calculate weather rather than Simple Weather algorithm

### ISSUE THREAD

**Issue by marcusadmortati** [dovrosenberg/foundry-simple-weather#9] opened 2023-10-21 17:28 UTC
That can generate the weather linked to custom tables.

**Comment by dovrosenberg** [comment] 2023-10-22 02:06
Can you explain in more detail what you're hoping for?

**Comment by marcusadmortati** [comment] 2023-10-22 16:18
Explaining. The weather will be generated from tables created by the user, that is, the results such as: rain, fog, cloudy, will be generated from tables that I create.

**Comment by dovrosenberg** [comment] 2023-10-22 17:08
The way it works today isn't just a random roll. It moves around essentially a grid of possible weather, which is what allows the changes to make sense. For example, it won't move from unseasonably warm to cold without going through a middle state or two first.

I could let you load your own descriptions and temperatures to populate that grid, but they have to be positioned properly or you'll get strange changes, so it's non trivial. 

But it sounds like you just want it to randomly pick from a table? I'm curious what the advantage is to using this module then vs just using a roll table. Is it the chat? Or the auto trigger from simple calendar? Just thinking through the different use cases...

Also, would you propose different tables for different biomes? Different seasons?

Appreciate the input.

**Comment by marcusadmortati** [comment] 2023-10-22 17:16
Yes, I have tables (and their variants, by season, biome) that I roll at the beginning of the day that result in, for example, rain (the time it starts and the duration of this rain)...

**Comment by marcusadmortati** [comment] 2023-10-22 17:24
[https://i.imgur.com/BBjL48k.jpeg](url)
My table for temperate climates, with its subtables and the chat output.

**Comment by dovrosenberg** [comment] 2023-10-22 22:30
Thanks.  I think I see.  It looks like a very robust system.  I love people wanting to use Simple Weather, of course, but I think I'm missing why you'd want to vs. using the roll tables?  Is it just the connection to Simple Calendar?

**Comment by marcusadmortati** [comment] 2023-10-22 22:54
Yes, he would call the tables rolling at the turn of the day.

**Comment by dovrosenberg** [comment] 2023-10-23 00:30
Got it.  I'm new to Foundry and I don't know enough about roll tables to think through the implications of how I'd make this work or what the options would be.  But I will take a look and try to learn more.  I may have some more questions once I do that.

**Comment by dovrosenberg** [comment] 2024-01-11 11:33
The way I'm thinking about handling this is with some sort of add-on modules that could replace the logic of what weather to pick.  This way specific tables like yours or for a particular system could be built and you'd still be able to use this module as the trigger and to handle the FX generation.  As a result, I'm closing this issue as now being a duplicate of #27

**Closed by dovrosenberg** 2024-01-11 11:33 UTC
Labels: enhancement, under consideration
